fix: bump tikisdk 3.0.0
tiki/apps-receipt-capacitor pull request #340
Opened 2023-10-17 19:29 UTC by ricardobrg

Fix iOS sdk initialization

2023-10-17 20:04 UTC, timoguin requested changes

2023-10-17 20:04 UTC, timoguin commented on makefile
> +	cd example/vue3/ios/App pod deintegrate
Missing an `&&` here, I think.

2023-10-17 20:04 UTC, timoguin commented on makefile
> +	cd example/vue2/ios/App pod deintegrate
Also missing an `&&` here.

2023-10-18 00:54 UTC, ricardobrg commented on makefile
> +	cd example/vue3/ios/App pod deintegrate
fixed... in line 26 it was missing too

2023-10-18 00:56 UTC, timoguin approved these changes
👍

2023-10-18 00:57 UTC, merged